# Generated by Django 3.2.2 on 2021-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='کد'),
        ),
    ]
