# Generated by Django 3.2.2 on 2021-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(default=10, verbose_name='درصد تخفیف'),
            preserve_default=False,
        ),
    ]
