# Generated by Django 3.2.2 on 2021-12-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0006_couponuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('UD', 'دلار'), ('TM', 'تومان')], default='TM', max_length=2, verbose_name='نوع'),
        ),
    ]
