# Generated by Django 3.2.2 on 2021-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک کاربران', 'verbose_name_plural': 'اشتراک های کاربران'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
        migrations.AlterField(
            model_name='type',
            name='time',
            field=models.PositiveBigIntegerField(verbose_name='مدت زمان'),
        ),
    ]
