# Generated by Django 3.2.2 on 2021-07-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_auto_20210730_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='Subscription.type', verbose_name='نوع اشتراک'),
        ),
    ]
