# Generated by Django 3.2.2 on 2021-07-30 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subscription', '0003_alter_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='type', to='Subscription.type', verbose_name='نوع اشتراک'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='type',
            name='time',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='مدت زمان'),
        ),
    ]
