# Generated by Django 3.2.2 on 2021-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0008_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت'),
        ),
    ]
