# Generated by Django 3.2.2 on 2021-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0009_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='نامک'),
        ),
    ]
