# Generated by Django 3.2.6 on 2021-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0012_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('full', 'کامل'), ('view', 'فقط تماشا')], default='movie', max_length=11, verbose_name='نوع اشتراک'),
        ),
    ]
