# Generated by Django 3.2.2 on 2021-08-11 19:38

import Category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Category.models.upload_image, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='نامک'),
        ),
    ]
