# Generated by Django 3.2.2 on 2021-08-11 20:02

import Category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20210812_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=Category.models.upload_image, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='نامک'),
        ),
    ]
