# Generated by Django 3.2.2 on 2021-08-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_auto_20210812_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='dfgfdg', max_length=500, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
