# Generated by Django 3.2.2 on 2021-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(verbose_name='قسمت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='time',
            field=models.IntegerField(verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
