# Generated by Django 3.2.2 on 2021-08-03 09:32

import Episode.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0002_auto_20210803_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(upload_to=Episode.models.upload_image, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(upload_to=Episode.models.upload_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='فیلم'),
        ),
    ]
