# Generated by Django 3.2.2 on 2021-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0004_alter_episode_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید'),
        ),
    ]
