# Generated by Django 3.2.2 on 2021-08-04 11:14

import Episode.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0005_alter_episode_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Episode.models.upload_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='فیلم'),
        ),
    ]
