# Generated by Django 3.2.2 on 2021-08-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0006_alter_episode_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='فیلم'),
        ),
    ]
