# Generated by Django 3.2.2 on 2021-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0007_alter_episode_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='نامک'),
        ),
    ]
