# Generated by Django 3.2.2 on 2021-08-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0009_alter_episode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='actors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بازیگران'),
        ),
        migrations.AddField(
            model_name='episode',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محصول کشور'),
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کارگردان'),
        ),
        migrations.AddField(
            model_name='episode',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ژانر'),
        ),
        migrations.AddField(
            model_name='episode',
            name='imdb_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='امتیاز imdb'),
        ),
        migrations.AddField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('educational', 'آموزشی'), ('movie', 'فیلم')], default='educational', max_length=11, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استاد'),
        ),
    ]
