# Generated by Django 3.2.2 on 2021-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0010_auto_20210813_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
