# Generated by Django 3.2.2 on 2021-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0011_alter_episode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('educational', 'آموزشی'), ('movie', 'فیلم')], default='movie', max_length=11, verbose_name='نوع'),
        ),
    ]
