# Generated by Django 3.2.2 on 2021-08-14 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0016_alter_episode_imdb_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='imdb_score',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.RegexValidator(message='امتیاز imdb باید عددی باشد', regex='^([1-9])$[+-]?([0-9]*[.])?[0-9]+')], verbose_name='امتیاز imdb'),
        ),
    ]
