# Generated by Django 3.2.2 on 2021-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0018_alter_episode_imdb_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='imdb_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='امتیاز imdb'),
        ),
    ]
