# Generated by Django 3.2.2 on 2021-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0019_alter_episode_imdb_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='construction_year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سال ساخت'),
        ),
    ]
