# Generated by Django 3.2.2 on 2021-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0020_episode_construction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(blank=True, null=True, verbose_name='قسمت'),
        ),
    ]
