# Generated by Django 3.2.6 on 2021-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0021_alter_episode_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_mp4',
            field=models.TextField(blank=True, null=True, verbose_name='لینک دانلود (mp4)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='فیلم (json)'),
        ),
    ]
