# Generated by Django 3.2.2 on 2021-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0022_auto_20210826_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_mp4',
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='لینک دانلود (mp4)'),
        ),
    ]
