# Generated by Django 3.2.2 on 2021-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0023_auto_20210915_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قسمت'),
        ),
    ]
