# Generated by Django 3.2.2 on 2021-12-04 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Episode', '0026_auto_20211202_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_downloads', to='Episode.episode', verbose_name='قسمت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_downloads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ویدیو دانلود شده',
                'verbose_name_plural': 'ویدیوها دانلود شده',
            },
        ),
    ]
