# Generated by Django 3.2.2 on 2021-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_passwordreset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='آیا استفاده شده است'),
        ),
    ]
