# Generated by Django 3.2.2 on 2021-08-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='as@gmail.com', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
