# Generated by Django 3.2.2 on 2021-08-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
