# Generated by Django 3.2.2 on 2021-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_watching',
            field=models.BooleanField(default=False, verbose_name='is watching'),
        ),
    ]
