# Generated by Django 3.2.2 on 2021-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_is_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='phone'),
        ),
    ]
